
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.abnhl.notebook_movil.model.analizadores.codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLOT = 4;
  public static final int MENOS = 9;
  public static final int PUNTO = 16;
  public static final int CADENA = 20;
  public static final int PARENT_IZQ = 14;
  public static final int DECIMAL = 18;
  public static final int PARENT_DER = 15;
  public static final int POW = 12;
  public static final int ID = 17;
  public static final int OPERADORES = 6;
  public static final int ASIGNACION = 13;
  public static final int EOF = 0;
  public static final int MULT = 10;
  public static final int DIV = 11;
  public static final int PRINT = 2;
  public static final int error = 1;
  public static final int REPORTES = 5;
  public static final int FORMAT = 3;
  public static final int ENTERO = 19;
  public static final int ERRORES = 7;
  public static final int MAS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "FORMAT",
  "PLOT",
  "REPORTES",
  "OPERADORES",
  "ERRORES",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "POW",
  "ASIGNACION",
  "PARENT_IZQ",
  "PARENT_DER",
  "PUNTO",
  "ID",
  "DECIMAL",
  "ENTERO",
  "CADENA"
  };
}

